Implement Article page, and article, comment components
osamhack2021/web_military-in_osambulgogi pull request #5
Opened 2021-10-07 20:31 UTC by juhy0987

게시글 페이지, 댓글 컴포넌트를 포함하여 부대 커뮤니티 홈, 오픈 커뮤니티 게시판 모음 등을 포함

2021-10-07 20:32 UTC, juhy0987 commented
ㅈ될뻔했다.. 작업한거 리베이스 했다가 싹다 날아갈 뻔
20분 동안 뇌정지 왔다가 겨우 돌림

2021-10-08 07:50 UTC, kangrnin requested changes

2021-10-08 07:50 UTC, kangrnin commented on frontend/components/Article.vue
> +            :test-data="testDatas[index]"
Comment 컴포넌트는 다른거 없이 prop으로 받은 데이터를 띄워주기만 하면 더 간결할듯 (순수 디스플레이용)
지금은  Comment들이 각자 rest 요청 하고있는데, Article에서 fetch할때 글 내용하고 같이 댓글들도 한번에 불러오도록 하고 test-data를 data로 이름 바꿔서 그걸로 바로 내용 띄우면 좋을거같아

2021-10-08 07:50 UTC, kangrnin commented on frontend/components/Article.vue
> +            :is-even="index % 2 != 0"
프로토타입 보니까 배경 흰색/회색 기준이 번갈아서가 아닌것같던데 수정좀
(본인이 쓴 댓글 강조용인가?)

2021-10-08 07:50 UTC, kangrnin commented on frontend/components/Article.vue
> +          isCcc: false
Ccc가 무슨 약자인지 모르겠어
변수명 길어도 괜찮으니까 isNestedComment나 아님 약자 풀은걸로 수정부탁

2021-10-08 07:50 UTC, kangrnin commented on frontend/components/Comment.vue
> +          >답글</Nuxtlink
대댓글 달때 새로운 페이지로 이동하는 대신 댓글 밑에 작은 입력창 하나 띄워서 작성완료하면 저 링크로 POST 보내자

2021-10-08 07:50 UTC, kangrnin commented on frontend/components/ArticleBlock.vue
> +      this.reportDate = this.articleData.reportDate
여기도 임시로 articleData 넘겨서 서버에서 받아오는거 대신한거같은데 ArticleBlock 컴포넌트도 순수 디스플레이용으로 만들어줘
board/open 페이지에서 게시글 데이터 다 받고, 여기는 props로 텍스트만 받아서 띄워주고
+ vote나 nuxtlink 때문에 boardId랑 articleId도 받아야겠네. articleData에 합치면 될듯

2021-10-08 07:50 UTC, kangrnin commented on frontend/components/BoardBlock1.vue
> +        2021.09.27(월) 15:20
이름 적당한걸로 바꾸고. 이것도 하드코딩 대신 데이터 받아서 표시하도록 수정해야됨

2021-10-08 07:50 UTC, kangrnin commented on frontend/components/BoardBlock2.vue
> +      to="/board/:id/article/article-id"
이것도 boardId랑 comments 받아서 띄우면 될듯

2021-10-08 07:50 UTC, kangrnin commented on frontend/pages/board/group/index.vue
> +    <div class="flex-none w-160 items-center justify-center space-y-8">
이 페이지는 /board/group이 아니라 /home이나 /dashboard로 해야돼(=>BoardSearch같은거 이름도 바꿔야함)
/board/group은 커뮤니티의 장병게시판

그리고 board/open, board/group으로 게시판마다 페이지 따로 만들지 말고 board/:boardId 에 만드는게 좋을듯
하나의 패이지로 boardId 받아서 그때그때 내용만 다르게 표시할 수 있게

2021-10-08 07:50 UTC, kangrnin commented on frontend/pages/board/index.vue
> +<template>
/board로 가면 /board/1같은걸로 리디렉션해야 맞을듯
게시판 총괄하는(?)그런 페이지는 없으니까

2021-10-08 08:01 UTC, juhy0987 commented on frontend/components/Article.vue
> +            :is-even="index % 2 != 0"
is even은 배경땜에 넣은게 맞음 근데 대댓글포함 흰/회 번갈아가면서 나오도록 한거

2021-10-08 08:01 UTC, juhy0987 commented on frontend/components/Article.vue
> +            :test-data="testDatas[index]"
ㅇㅋ

2021-10-08 08:02 UTC, juhy0987 commented on frontend/components/Article.vue
> +          isCcc: false
저거 쓸땐 그냥 귀찮아서 쓴거라 바꿔놓음

2021-10-08 08:02 UTC, juhy0987 commented on frontend/components/Comment.vue
> +          >답글</Nuxtlink
별도의 컴포넌트 만들 필요는 없나

2021-10-08 08:04 UTC, juhy0987 commented on frontend/components/ArticleBlock.vue
> +      this.reportDate = this.articleData.reportDate
저거 원래 boardId랑 articleId만 넘기고 데이터는 블럭에서 받은걸로 하려했는데
아직 불러올 수가 없어서 넣은거

2021-10-08 08:04 UTC, juhy0987 commented on frontend/components/BoardBlock1.vue
> +        2021.09.27(월) 15:20
저 부분은 깜박해썌네

2021-10-08 08:05 UTC, kangrnin commented on frontend/components/Comment.vue
> +          >답글</Nuxtlink
컴포넌트 하나 더 만들어서 답글달때 show하면 될듯
아님 comment컴포넌트 자체에서 만들어도되고

2021-10-08 08:11 UTC, kangrnin commented on frontend/components/ArticleBlock.vue
> +      this.reportDate = this.articleData.reportDate
근데 이제 데이터를 블럭에서는 아예 받지 말고 상위 컴포넌트에서 한번에 받은 다음에 블럭은 텍스트 띄우기만 하면 되는거지

2021-10-08 08:22 UTC, juhy0987 commented on frontend/components/BoardBlock2.vue
> +      to="/board/:id/article/article-id"
comments???

2021-10-08 08:23 UTC, juhy0987 commented on frontend/pages/board/group/index.vue
> +    <div class="flex-none w-160 items-center justify-center space-y-8">
그럼 이거 pages 에 어떻게 넣어야되지

2021-10-08 09:02 UTC, kangrnin commented on frontend/components/BoardBlock2.vue
> +      to="/board/:id/article/article-id"
아 article

2021-10-08 09:03 UTC, kangrnin commented on frontend/pages/board/group/index.vue
> +    <div class="flex-none w-160 items-center justify-center space-y-8">
pages/home에 넣자

2021-10-08 09:31 UTC, merged

2021-10-09 00:11 UTC, juhy0987 commented on frontend/components/Comment.vue
> +          >답글</Nuxtlink
comment 자체에서 만들도록 했음
굳이 하나 더 만드는건 손해 같아서
>> 생각해보니까 nested 댓글 뿐만아니라 일반 댓글도 달아야 되서
그냥 컴포넌트 하나 더 만듬

2021-10-09 07:44 UTC, juhy0987 commented on frontend/pages/board/index.vue
> +<template>
이거 route 어떻게 연결하지 그냥 Nuxtlink로 이어?