Article, Board base components
osamhack2021/web_military-in_osambulgogi pull request #9
Opened 2021-10-14 14:59 UTC by juhy0987

게시글, 게시판에 대한 기본 페이지 구성 및 부대 게시판 홈에 대한 틀을 포함하는 컴포넌트
>> 단, api path는 미 적용 상태

2021-10-15 15:00 UTC, dotoleeoak requested changes

2021-10-15 15:00 UTC, dotoleeoak commented on frontend/components/Dropdown.vue
> +      selectedIndex: this.selected
이렇게 하면 `selectedIndex`는 초기화만 되고 업데이트 안되니까 `computed`로 옮겨야할 듯

2021-10-15 15:00 UTC, dotoleeoak commented on frontend/components/Dropdown.vue
> +      selectedIndex: this.selected
근데 애초에 이 컴포넌트 강민이가 다른 곳에서 많이 썼을거 같은데 이렇게 수정해도 되나 모르겠다

2021-10-15 15:00 UTC, dotoleeoak commented on frontend/tailwind.config.js
> +        militaryDark: '#1E481D'
이건 왜 추가했어?

2021-10-16 03:43 UTC, kangrnin commented
board/article 라우팅이 잘못되어있음
ArticleBlock.vue에서는 NuxtLink가 /board/id/article/article-id로 되어있는데 article 페이지는 현재 경로가 /board/article임
+ article 페이지에서 수정 누르면 맨처음에 드랍다운이 빈칸으로 되어있음

2021-10-16 03:59 UTC, kangrnin requested changes

2021-10-16 03:59 UTC, kangrnin commented on frontend/components/ArticleBlock.vue
> +  <Nuxtlink
NuxtLink

2021-10-16 03:59 UTC, kangrnin commented on frontend/pages/board/index.vue
> +      <Nuxtlink
NuxtLink

2021-10-16 03:59 UTC, kangrnin commented on frontend/pages/board/index.vue
> +      <Nuxtlink to="/board:/id" class="text-2xl text-gray-400 font-bold"
/board/:id

2021-10-16 03:59 UTC, kangrnin commented on frontend/pages/board/index.vue
> +      <Nuxtlink to="/board:/id" class="text-2xl text-gray-400 font-bold"
현재 보고있는 board에 따라서 하이라이트된 글씨가 달라져야 함

2021-10-16 03:59 UTC, kangrnin commented on frontend/pages/board/index.vue
> +      <Nuxtlink to="/board:/id" class="text-2xl text-gray-400 font-bold"
그리고 /board/:id에 해당하는 라우팅 자체가 안되어있음
pages/board/_id.vue를 만들고 그 안에서 this.$route.params.id으로 url의 id값 가져올 수 있음

https://nuxtjs.org/docs/features/file-system-routing/

2021-10-16 03:59 UTC, kangrnin commented on frontend/components/Article.vue
> +        to="/board"
/board가 아니라 현재 article이 속한 board로 이동해야함 (/board/:boardId)

url을 /board/:boardId/article/:articleId로 구성하면 article 페이지에서 자신이 속한 boardId 바로 가져올 수 있을것임

2021-10-16 03:59 UTC, kangrnin commented on frontend/components/Article.vue
> +    this.boardId = await new Promise((resolve) => resolve())
서버로부터 데이터를 받아오기 위한 사전 정보인 boardId랑 articleId는 fetch하는 게 아니라 url상에서 가져와야함
그러고 나서 boardId랑 articleId를 사용해서 나머지 정보를 받아와야함

(우리 API Docs에서 게시글 불러오기 api에서도 parameter로 id(articleId), boardId가 필요함)

2021-10-16 03:59 UTC, kangrnin commented on frontend/components/Dropdown.vue
> +      selectedIndex: this.selected
기존거랑 호환돼서 바꿔도 괜찮을듯

2021-10-17 00:01 UTC, juhy0987 commented on frontend/tailwind.config.js
> +        militaryDark: '#1E481D'
hover 액션

2021-10-17 00:02 UTC, juhy0987 commented on frontend/components/ArticleBlock.vue
> +  <Nuxtlink
굿

2021-10-17 00:02 UTC, juhy0987 commented on frontend/pages/board/index.vue
> +      <Nuxtlink
굿

2021-10-17 00:03 UTC, juhy0987 commented on frontend/pages/board/index.vue
> +      <Nuxtlink to="/board:/id" class="text-2xl text-gray-400 font-bold"
오 ㄳㄳ

2021-10-17 00:05 UTC, juhy0987 commented on frontend/components/Article.vue
> +    this.boardId = await new Promise((resolve) => resolve())
이건 api path 적용하기 전에 내용 넣을려고 적어둔거

2021-10-17 06:08 UTC, juhy0987 commented on frontend/components/Article.vue
> +        to="/board"
parameter 붙이는거 어떻게 하는 지 도통 모르겠네

2021-10-17 06:08 UTC, juhy0987 commented
NuxtLink 경로 다 이상하게 되어 있을텐데 어디로 해야하는 지 몰라서 그러는게 아니라
어떻게 하는 지 몰라서 못한 거임;;

2021-10-17 06:26 UTC, juhy0987 commented on frontend/components/Article.vue
> +        to="/board"
Nuxtlink api 어디로 붙여야 되는 지 몰라서 안붙인게 아님;; 그만 말해

2021-10-17 15:14 UTC, juhy0987 commented on frontend/components/Dropdown.vue
> +      selectedIndex: this.selected
이거 그럼 computed로 옮겨서 완성??

2021-10-17 15:20 UTC, closed without merging